### PR TITLE
Add dev excuses

### PR DESCRIPTION
**Pull request by dshoreman**
Adds `liona: [developer ]excuse[ me]` commands to liona, as requested by grafi:

    [22:22:12] <grafi> lagbox https://github.com/github/hubot-scripts/blob/master/src/scripts/excuse.coffee i want that for liona
    [22:22:34] <grafi> with more programmery statements

### CODE REVIEW

**Comment by dshoreman** [comment]
Already on the dance branch I didn't know existed. FML

**Comment by dshoreman** [comment]
@lagbox Whaddaya think about changing `(?:developer excuse|excuse)` to `(?:dev excuse|developer excuse|excuse)`? Adds a shorter 'dev excuse' but since 'excuse' is already shorter, could be kinda pointless...

**Comment by lagbox** [comment]
What sound does a grape make when you squash it?
It just lets out a little wine.

**Comment by dshoreman** [comment]
Squished, with a heavy brick.

**Comment by lagbox** [comment]
So much wine. The git god's will be happy.

**Pull request merged**
