### PR TITLE
Add a !dump trigger

### PR DESCRIPTION
**Pull request by HipsterJazzbo**
For the one million people a day that ask why their classes are not found. Not sure about the wording I put in there.

### CODE REVIEW

**Comment by JosephSilber** [comment]
Type `composer dump` in your terminal to have composer update its reference to your classes.

**Comment by HipsterJazzbo** [comment]
@JosephSilber That's better. I've tweaked it. THX.

**Comment by JosephSilber** [comment]
@HipsterJazzbo I purposefully had "composer dump" in there. No need for the autoload part. Just more typing, and more stuff to get wrong.

**Comment by HipsterJazzbo** [comment]
@JosephSilber There ya go.

**Comment by HipsterJazzbo** [comment]
So, um...

**Comment by lagbox** [comment]
It looks good. Are we happy with the wording ?

**Comment by machuga** [comment]
Hey guys sorry I'm missing notifications from PRs. This seems good.

**Pull request merged**
