### PR TITLE
Fix for new Google layout

### PR DESCRIPTION
**Pull request by daftspunk**
They use div.g now instead of li.g but oddly still wrap with ol

### CODE REVIEW

**Comment by machuga** [comment]
Oh that's really weird of them. Should we just make it .g in case it changes back?

**Comment by dshoreman** [comment]
I don't know how often they change things but it looks like the `<ol>` has an id of "rso". Perhaps we could use that?

Something like `ol#rso .g` should work as far as I can tell.

**Comment by machuga** [comment]
Okay let's use #rso .g for the selector then.

**Comment by lagbox** [comment]
did they change it again ?

**Pull request closed without merging**
